### ISSUE TITLE
Complete dataset(including images) for download?

### ISSUE THREAD

**Issue by rashmimilan** [manoja328/TallyQA_dataset#2]
Where can I actually find the complete dataset for download? 
Thanks.

{'answer': 4,
  'data_source': 'imported_genome',
  'image': 'VG_100K_2/2410408.jpg',
  'image_id': 92410408,
  'issimple': False,
  'question': 'How many headlights does the black bus have?',
  'question_id': 30095774}

**Comment by manoja328** [comment]
Hi, The images can be downloaded from Visual Genome and VQA websites.

**Comment by rashmimilan** [comment]
> Hi, The images can be downloaded from Visual Genome and VQA websites.

Thank you!
