### ISSUE TITLE
LICENSE please

### ISSUE THREAD

**Issue by lucasb-eyer** [manoja328/TallyQA_dataset#4]
Hi, could you please provide a license for this dataset? Not the images, since they are not yours, but your json train/test files.

Ideally you just upload a LICENSE file to the repo and mention it in the README. If you want broad usage of the dataset, I'd recommend one of Apache2/MIT/BSD, in that order of recommendation.

Cheers!

**Comment by manoja328** [comment]
Thanks for the recommendation.
